services:
  - type: web
    name: newsandniche-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_BASE_URL
        sync: false
      - key: NEXT_PUBLIC_GA_ID
        sync: false
    healthCheckPath: /
    autoDeploy: true 